development:
  :verbose: true
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 1 %>
staging:
  :verbose: true
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 1 %>
production:
  :verbose: true
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 1 %>
  :timeout: 8

:queues:
  - default
  - low
  - mailers
